import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  FR: {
    // Header & Ticker
    clientSpace: "Espace Client",
    memberSpace: "Espace Membre",
    login: "Se connecter",
    register: "S'inscrire",
    language: "Français",

    // Nav Labels
    navHome: "Accueil",
    navAbout: "À Propos",
    navServices: "Services",
    navMarkets: "Marchés",
    navExplore: "Explorer",
    navExplorer: "Explorer",
    navPortfolio: "Portefeuille",
    navTrading: "Trading",
    navNews: "Actualités",
    navEducation: "Éducation",
    navCommunity: "Communauté",
    navSupport: "Support",
    navContact: "Contact",
    categoryRubric: "Rubrique",
    languageSelect: "Langue",

    // Dropdown sub-items
    dropMarketOverview: "Vue d'ensemble du marché",
    dropNews: "Actualités principales",
    dropMainIndices: "Indices principaux",
    dropPopStocks: "Actions populaires",
    dropStocks: "Actions",
    dropEtfs: "ETF (Fonds Indiciels)",
    dropBonds: "Obligations",
    dropCommodities: "Matières premières",
    dropForex: "Devises (Forex)",
    dropStockSearch: "Recherche d'actions",
    dropListedCompanies: "Entreprises cotées",
    dropSectors: "Secteurs d'activité",
    dropRankings: "Gagnants / Perdants",
    dropMyInvestments: "Mes investissements",
    dropAssetAllocation: "Répartition des actifs",
    dropPerformance: "Performance",
    dropOrderHistory: "Historique des ordres",
    dropBuy: "Acheter des titres",
    dropSell: "Vendre des titres",
    dropPendingOrders: "Ordres en attente",
    dropEconomy: "Économie",
    dropCompanies: "Entreprises",
    dropFinancialAnalyses: "Analyses de marché",
    dropHistory: "Notre Histoire",
    dropTeam: "Notre Équipe",
    dropAgreements: "Nos Agréments",

    // Hero — Coming Soon Message
    heroComingSoonLine1: "Notre site complet",
    heroComingSoonAccent: "sera bientôt disponible.",

    // Hero Section Slides
    heroSlide1Badge: "Société de Bourse Agréée • Zone CEMAC",
    heroSlide1TitleLine1: "INVESTIR AUJOURD’HUI.",
    heroSlide1TitleAccent: "PATRIMOINE DE DEMAIN",
    heroSlide1Desc: "Accédez directement aux meilleures opportunités de la BVMAC avec le soutien de nos experts certifiés COSUMAF.",

    heroSlide2Badge: "Gestion de Patrimoine & Conseil",
    heroSlide2TitleLine1: "FAITES FRUCTIFIER",
    heroSlide2TitleAccent: "VOS AVOIRS & ACTIFS",
    heroSlide2Desc: "Optimisez vos placements, sécurisez vos actifs et profitez d'une stratégie d'investissement sur-mesure.",

    heroSlide3Badge: "Marché Financier Régional",
    heroSlide3TitleLine1: "FINANCER LA CROISSANCE",
    heroSlide3TitleAccent: "DES ENTREPRISES & ÉTATS",
    heroSlide3Desc: "Accompagnement stratégique des entreprises et institutions pour leurs levées de fonds et émissions obligataires.",

    heroBadge: "Société de Bourse Agréée • Zone CEMAC",
    heroTitleMain: "Votre Société de Bourse",
    heroTitleSub: "en Afrique Centrale",
    heroDescSub: "Agréée COSUMAF, membre de la BVMAC — investissez avec confiance dans les marchés financiers de la CEMAC grâce à nos experts certifiés.",
    openAccount: "OUVRIR UN COMPTE",
    bookAppointment: "DEMANDER UN RENDEZ-VOUS",
    satisRate: "Taux de Satisfaction",
    yearsExp: "Ans d'Expérience",
    stat1Label: "ANS D'EXPÉRIENCE",
    stat2Label: "CLIENTS NOUS FONT CONFIANCE",
    stat3Label: "TAUX DE SATISFACTION",
    stat4Label: "EXPERTS CERTIFIÉS",

    // Why Choose Us
    aboutUsTag: "À Propos de Nous",
    aboutUsHeading: "Nous Sommes une Société de Bourse",
    aboutUsHeadingAccent: "Dédiée à Votre Succès",
    aboutUsDesc: "Depuis 5 ans, OMYA INVEST accompagne ses clients avec rigueur, transparence et une profonde connaissance des marchés financiers de la CEMAC. Agréée par la COSUMAF, nous vous offrons un accès direct à la BVMAC et aux meilleures opportunités d'investissement.",
    secRegTitle: "Sécurité & Réglementation",
    secRegDesc: "Société de bourse agréée par la COSUMAF. Vos fonds sont ségrégués et protégés conformément aux normes CEMAC.",
    perfTitle: "Performance & Rendement",
    perfDesc: "Nos portefeuilles gérés surperforment régulièrement les indices de référence sur les marchés régionaux.",
    yearsExpTitle: "5 Ans d'Expérience",
    yearsExpDesc: "Expert en marchés financiers CEMAC — Brazzaville, Congo.",
    clientTrustCount: "Clients nous font confiance",
    discoverServices: "Découvrir Nos Services",
    whyTitle: "POURQUOI CHOISIR",
    whyTitleGold: "OMYA INVEST ?",
    whyDesc: "Notre expertise, notre indépendance et notre engagement envers nos clients font de nous un partenaire de confiance pour atteindre vos objectifs financiers.",

    // Activities Section
    missionVisionTag: "Notre Mission & Vision",
    missionVisionHeading: "Découvrez les Principes Fondamentaux Qui Nous Guident",
    whatWeDoTag: "Ce Que Nous Faisons",
    whatWeDoDesc: "Nous accompagnons nos clients avec rigueur, transparence et une profonde connaissance des marchés d'Afrique Centrale.",
    activitiesTitle: "NOS ACTIVITÉS & SERVICES",
    learnMore: "EN SAVOIR PLUS",
    act1Title: "SOCIÉTÉ DE BOURSE",
    act1Desc: "Exécution d'ordres sur les marchés financiers, intermédiation boursière et accès aux meilleures opportunités.",
    act2Title: "GESTION DE PATRIMOINE",
    act2Desc: "Des solutions sur-mesure pour faire fructifier et sécuriser votre patrimoine.",
    act3Title: "CONSEIL FINANCIER",
    act3Desc: "Accompagnement stratégique pour vos décisions financières et vos projets d’entreprise.",
    act4Title: "INVESTISSEMENTS",
    act4Desc: "Accédez à des opportunités d’investissement locales et internationales.",

    // Markets Section
    marketsTag: "Données en Temps Réel",
    marketsTitle: "NOS MARCHÉS FINANCIERS",
    marketsSub: "Accédez en temps réel aux informations des principaux marchés et indices.",
    seeAllMarkets: "VOIR TOUS LES MARCHÉS",
    mapCentralAfrica: "Afrique Centrale",
    mapBEAC: "BEAC",
    mapBVMAC: "BVMAC",
    mapIntl: "Marchés internationaux",
    tabIndices: "INDICES",
    tabActions: "ACTIONS",
    tabObligations: "OBLIGATIONS",
    tabDevises: "DEVISES",
    trendText: "Tendance",
    seeMoreDetails: "VOIR PLUS DE DÉTAILS",

    // Products Section
    productsTag: "Solutions Sur-Mesure",
    productsTitle: "NOS PRODUITS D’INVESTISSEMENT",
    discover: "DÉCOUVRIR",
    prod1Title: "ACTIONS COTÉES",
    prod1Desc: "Investissez dans les entreprises cotées et bénéficiez du potentiel de croissance des marchés.",
    prod2Title: "OBLIGATIONS",
    prod2Desc: "Diversifiez votre portefeuille avec des titres à revenu fixe sécurisés.",
    prod3Title: "OPCVM / FCP",
    prod3Desc: "Accédez à des fonds communs de placement gérés par nos experts.",
    prod4Title: "TITRES PUBLICS",
    prod4Desc: "Des placements sûrs émis par les États pour des revenus réguliers.",
    prod5Title: "PRIVATE EQUITY",
    prod5Desc: "Accompagnement et prises de participation dans des entreprises non cotées à fort potentiel.",

    // News, Simulator & Partners
    newsTitle: "ACTUALITÉS FINANCIÈRES",
    seeAllNews: "VOIR TOUTES",
    simTitle: "SIMULATEUR D’INVESTISSEMENT",
    amountToInvest: "Montant à investir",
    durationLabel: "Durée",
    yearSuffix: "ans",
    estimatedRate: "Taux estimatif",
    estimatedResult: "Capital final estimé",
    calculateBtn: "CALCULER MON RENDEMENT",
    partnersTitle: "NOS PARTENAIRES",
    seeAllPartners: "VOIR TOUS",

    // Testimonials & Footer
    testimonialsTag: "Confiance & Satisfaction",
    testimonialsTitle: "CE QUE DISENT NOS CLIENTS",
    ourTeamTitle: "Notre Équipe d'Experts",
    availableBadge: "Disponible",
    ctaTitle: "Parlons de Vos Objectifs Financiers & Obtenez une",
    ctaTitleAccent: "Consultation Gratuite",
    ctaDesc: "Nos experts certifiés COSUMAF sont disponibles pour analyser votre situation et vous proposer une stratégie d'investissement adaptée à vos objectifs.",
    getConsultation: "Obtenir une Consultation",
    quickLinks: "LIENS RAPIDES",
    servicesLinks: "SERVICES",
    addressHoursTitle: "Adresse & Horaires",
    openDaysTitle: "Jours Ouverts",
    openDaysValue: "Lun – Ven : 08h00 – 17h00",
    contactUs: "CONTACTEZ-NOUS",
    newsletterTitle: "NEWSLETTER",
    newsletterDesc: "Recevez nos analyses et actualités financières chaque semaine.",
    emailPlaceholder: "Votre adresse email",
    footerRights: "© 2024 OMYA INVEST. Tous droits réservés.",
    legalMentions: "Mentions légales",
    privacyPolicy: "Politique de confidentialité",
    siteMap: "Plan du site",

    // Auth Modal
    authModalLoginTitle: "Accéder à votre Espace",
    authModalRegisterTitle: "Créer votre Compte",
    authModalLoginDesc: "Connectez-vous pour suivre vos investissements et gérer votre portefeuille.",
    authModalRegisterDesc: "Rejoignez OMYA INVEST et accédez aux opportunités boursières.",
    orByEmail: "ou par email",
    fullName: "Nom Complet",
    emailAddr: "Adresse Email",
    passwordLabel: "Mot de passe",
    forgotPass: "Oublié ?",
    investorType: "Type d'Investisseur",
    particulier: "Investisseur Particulier",
    corporate: "Entreprise / Institutionnel",
    rememberMe: "Se souvenir de moi",
    acceptTerms: "J’accepte les conditions d’utilisation",
    submitLogin: "SE CONNECTER",
    submitRegister: "S’INSCRIRE",
  },

  PT: {
    // Header & Ticker
    clientSpace: "Área do Cliente",
    memberSpace: "Área de Membro",
    login: "Entrar",
    register: "Registrar",
    language: "Português",

    // Nav Labels
    navHome: "Início",
    navAbout: "Sobre Nós",
    navServices: "Serviços",
    navMarkets: "Mercados",
    navExplore: "Explorar",
    navExplorer: "Explorar",
    navPortfolio: "Carteira",
    navTrading: "Negociação",
    navNews: "Notícias",
    navEducation: "Educação",
    navCommunity: "Comunidade",
    navSupport: "Suporte",
    navContact: "Contato",
    categoryRubric: "Seção",
    languageSelect: "Idioma",

    // Dropdown sub-items
    dropMarketOverview: "Visão geral do mercado",
    dropNews: "Principais notícias",
    dropMainIndices: "Principais índices",
    dropPopStocks: "Ações populares",
    dropStocks: "Ações",
    dropEtfs: "ETF",
    dropBonds: "Obrigações",
    dropCommodities: "Commodities",
    dropForex: "Moedas (Forex)",
    dropStockSearch: "Pesquisa de ações",
    dropListedCompanies: "Empresas cotadas",
    dropSectors: "Setores de atividade",
    dropRankings: "Ganhadores / Perdedores",
    dropMyInvestments: "Meus investimentos",
    dropAssetAllocation: "Alocação de ativos",
    dropPerformance: "Desempenho",
    dropOrderHistory: "Histórico de ordens",
    dropBuy: "Comprar títulos",
    dropSell: "Vender títulos",
    dropPendingOrders: "Ordens pendentes",
    dropEconomy: "Economia",
    dropCompanies: "Empresas",
    dropFinancialAnalyses: "Análises de mercado",
    dropHistory: "Nossa História",
    dropTeam: "Nossa Equipe",
    dropAgreements: "Nossas Licenças",

    // Hero — Coming Soon Message
    heroComingSoonLine1: "Nosso site completo",
    heroComingSoonAccent: "estará disponível em breve.",

    // Hero Section Slides
    heroSlide1Badge: "Sociedade de Corretagem Autorizada • Zona CEMAC",
    heroSlide1TitleLine1: "INVESTIR HOJE.",
    heroSlide1TitleAccent: "PATRIMÔNIO DE AMANHÃ",
    heroSlide1Desc: "Acese diretamente as melhores oportunidades da BVMAC com o apoio de nossos especialistas certificados pela COSUMAF.",

    heroSlide2Badge: "Gestão de Patrimônio e Consultoria",
    heroSlide2TitleLine1: "FAÇA CRESCER SEUS",
    heroSlide2TitleAccent: "ATIVOS E RECURSOS",
    heroSlide2Desc: "Otimize seus investimentos, proteja seus ativos e aproveite uma estratégia personalizada sob medida.",

    heroSlide3Badge: "Mercado Financeiro Regional",
    heroSlide3TitleLine1: "FINANCIAR O CRESCIMENTO",
    heroSlide3TitleAccent: "DAS EMPRESAS E ESTADOS",
    heroSlide3Desc: "Acompanhamento estratégico de empresas e instituições públicas para captação de recursos e emissão de títulos.",

    heroBadge: "Sociedade de Corretagem Autorizada • Zona CEMAC",
    heroTitleMain: "Sua Sociedade de Corretagem",
    heroTitleSub: "na África Central",
    heroDescSub: "Autorizada pela COSUMAF, membro da BVMAC — invista com confiança nos mercados financeiros da CEMAC com nossos especialistas certificados.",
    openAccount: "ABRIR UMA CONTA",
    bookAppointment: "AGENDAR UMA REUNIÃO",
    satisRate: "Taxa de Satisfação",
    yearsExp: "Anos de Experiência",
    stat1Label: "ANOS DE EXPERIÊNCIA",
    stat2Label: "CLIENTES CONFIAM EM NÓS",
    stat3Label: "TAXA DE SATISFAÇÃO",
    stat4Label: "ESPECIALISTAS CERTIFICADOS",

    // Why Choose Us
    aboutUsTag: "Sobre Nós",
    aboutUsHeading: "Somos uma Sociedade de Corretagem",
    aboutUsHeadingAccent: "Dedicada ao Seu Sucesso",
    aboutUsDesc: "Há 5 anos, a OMYA INVEST acompanha seus clientes com rigor, transparência e profundo conhecimento dos mercados financeiros da CEMAC. Autorizada pela COSUMAF, oferecemos acesso direto à BVMAC.",
    secRegTitle: "Segurança e Regulamentação",
    secRegDesc: "Sociedade de corretagem autorizada pela COSUMAF. Seus fundos são protegidos de acordo com as normas CEMAC.",
    perfTitle: "Desempenho e Rendimento",
    perfDesc: "Nossas carteiras geridas superam regularmente os índices de referência nos mercados regionais.",
    yearsExpTitle: "5 Anos de Experiência",
    yearsExpDesc: "Especialista em mercados financeiros CEMAC — Brazzaville, Congo.",
    clientTrustCount: "Clientes confiam em nós",
    discoverServices: "Descobrir Nossos Serviços",
    whyTitle: "POR QUE ESCOLHER A",
    whyTitleGold: "OMYA INVEST ?",
    whyDesc: "Nossa experiência, independência e compromisso com nossos clientes nos tornam um parceiro de confiança para alcançar seus objetivos financeiros.",

    // Activities Section
    missionVisionTag: "Nossa Missão e Visão",
    missionVisionHeading: "Descubra os Princípios Fundamentais Que Nos Guiam",
    whatWeDoTag: "O Que Fazemos",
    whatWeDoDesc: "Acompanhamos nossos clientes com rigor, transparência e profundo conhecimento dos mercados da África Central.",
    activitiesTitle: "NOSSAS ATIVIDADES E SERVIÇOS",
    learnMore: "SAIBA MAIS",
    act1Title: "SOCIEDADE DE CORRETAGEM",
    act1Desc: "Execução de ordens nos mercados financeiros, intermediação e acesso às melhores oportunidades.",
    act2Title: "GESTÃO DE PATRIMÔNIO",
    act2Desc: "Soluções sob medida para fazer crescer e proteger seu patrimônio.",
    act3Title: "CONSULTORIA FINANCEIRA",
    act3Desc: "Acompanhamento estratégico para suas decisões financeiras e projetos empresariais.",
    act4Title: "INVESTIMENTOS",
    act4Desc: "Acesso a oportunidades de investimento locais e internacionais.",

    // Markets Section
    marketsTag: "Dados em Tempo Real",
    marketsTitle: "NOSSOS MERCADOS FINANCEIROS",
    marketsSub: "Acesse informações em tempo real sobre os principais mercados e índices.",
    seeAllMarkets: "VER TODOS OS MERCADOS",
    mapCentralAfrica: "África Central",
    mapBEAC: "BEAC",
    mapBVMAC: "BVMAC",
    mapIntl: "Mercados internacionais",
    tabIndices: "ÍNDICES",
    tabActions: "AÇÕES",
    tabObligations: "OBRIGAÇÕES",
    tabDevises: "MOEDAS",
    trendText: "Tendência",
    seeMoreDetails: "VER MAIS DETALHES",

    // Products Section
    productsTag: "Soluções Sob Medida",
    productsTitle: "NOSSOS PRODUTOS DE INVESTIMENTO",
    discover: "DESCOBRIR",
    prod1Title: "AÇÕES COTADAS",
    prod1Desc: "Invista em empresas cotadas e aproveite o potencial de crescimento dos mercados.",
    prod2Title: "OBRIGAÇÕES",
    prod2Desc: "Diversifique sua carteira com títulos de renda fixa seguros.",
    prod3Title: "OPCVM / FCP",
    prod3Desc: "Acesse fundos mútuos geridos por nossos especialistas.",
    prod4Title: "TÍTULOS PÚBLICOS",
    prod4Desc: "Investimentos seguros emitidos por Estados para rendimentos regulares.",
    prod5Title: "PRIVATE EQUITY",
    prod5Desc: "Investimentos diretos em empresas não cotadas com alto potencial.",

    // News, Simulator & Partners
    newsTitle: "NOTÍCIAS FINANCEIRAS",
    seeAllNews: "VER TODAS",
    simTitle: "SIMULADOR DE INVESTIMENTO",
    amountToInvest: "Valor a investir",
    durationLabel: "Duração",
    yearSuffix: "anos",
    estimatedRate: "Taxa estimada",
    estimatedResult: "Capital final estimado",
    calculateBtn: "CALCULAR MEU RENDIMENTO",
    partnersTitle: "NOSSOS PARCEIROS",
    seeAllPartners: "VER TODOS",

    // Testimonials & Footer
    testimonialsTag: "Confiança e Satisfação",
    testimonialsTitle: "O QUE DIZEM NOSSOS CLIENTES",
    ourTeamTitle: "Nossa Equipe de Especialistas",
    availableBadge: "Disponível",
    ctaTitle: "Fale sobre Seus Objetivos Financeiros e Obtenha uma",
    ctaTitleAccent: "Consultoria Gratuita",
    ctaDesc: "Nossos especialistas certificados pela COSUMAF estão disponíveis para analisar sua situação e propor uma estratégia adaptada.",
    getConsultation: "Obter uma Consultoria",
    quickLinks: "LINKS RÁPIDOS",
    servicesLinks: "SERVIÇOS",
    addressHoursTitle: "Endereço e Horários",
    openDaysTitle: "Dias Abertos",
    openDaysValue: "Seg – Sex: 08:00 – 17:00",
    contactUs: "CONTATE-NOS",
    newsletterTitle: "BOLETIM INFORMATIVO",
    newsletterDesc: "Receba nossas análises e notícias financeiras semanalmente.",
    emailPlaceholder: "Seu endereço de e-mail",
    footerRights: "© 2024 OMYA INVEST. Todos os direitos reservados.",
    legalMentions: "Avisos legais",
    privacyPolicy: "Política de privacidade",
    siteMap: "Mapa do site",

    // Auth Modal
    authModalLoginTitle: "Acessar sua Área",
    authModalRegisterTitle: "Criar sua Conta",
    authModalLoginDesc: "Faça login para acompanhar seus investimentos e gerenciar sua carteira.",
    authModalRegisterDesc: "Junte-se à OMYA INVEST e acesse oportunidades de mercado.",
    orByEmail: "ou por e-mail",
    fullName: "Nome Completo",
    emailAddr: "Endereço de E-mail",
    passwordLabel: "Senha",
    forgotPass: "Esqueceu?",
    investorType: "Tipo de Investidor",
    particulier: "Investidor Individual",
    corporate: "Empresa / Institucional",
    rememberMe: "Lembrar-me",
    acceptTerms: "Aceito os termos de serviço",
    submitLogin: "ENTRAR",
    submitRegister: "REGISTRAR-SE",
  },

  EN: {
    // Header & Ticker
    clientSpace: "Client Space",
    memberSpace: "Member Space",
    login: "Log In",
    register: "Sign Up",
    language: "English",

    // Nav Labels
    navHome: "Home",
    navAbout: "About Us",
    navServices: "Services",
    navMarkets: "Markets",
    navExplore: "Explore",
    navExplorer: "Explore",
    navPortfolio: "Portfolio",
    navTrading: "Trading",
    navNews: "News",
    navEducation: "Education",
    navCommunity: "Community",
    navSupport: "Support",
    navContact: "Contact",
    categoryRubric: "Category",
    languageSelect: "Language",

    // Dropdown sub-items
    dropMarketOverview: "Market Overview",
    dropNews: "Top Stories",
    dropMainIndices: "Key Indices",
    dropPopStocks: "Popular Stocks",
    dropStocks: "Stocks",
    dropEtfs: "ETFs",
    dropBonds: "Bonds",
    dropCommodities: "Commodities",
    dropForex: "Currencies (Forex)",
    dropStockSearch: "Stock Screener",
    dropListedCompanies: "Listed Companies",
    dropSectors: "Industry Sectors",
    dropRankings: "Gainers & Losers",
    dropMyInvestments: "My Holdings",
    dropAssetAllocation: "Asset Allocation",
    dropPerformance: "Performance",
    dropOrderHistory: "Order History",
    dropBuy: "Buy Securities",
    dropSell: "Sell Securities",
    dropPendingOrders: "Pending Orders",
    dropEconomy: "Economy",
    dropCompanies: "Corporate",
    dropFinancialAnalyses: "Market Analysis",
    dropHistory: "Our Story",
    dropTeam: "Our Team",
    dropAgreements: "Our Licenses",

    // Hero — Coming Soon Message
    heroComingSoonLine1: "Our full website",
    heroComingSoonAccent: "will be available soon.",

    // Hero Section Slides
    heroSlide1Badge: "Licensed Stock Brokerage • CEMAC Zone",
    heroSlide1TitleLine1: "INVEST TODAY.",
    heroSlide1TitleAccent: "WEALTH FOR TOMORROW",
    heroSlide1Desc: "Access premier BVMAC stock market opportunities with guidance from our COSUMAF certified experts.",

    heroSlide2Badge: "Wealth Management & Advisory",
    heroSlide2TitleLine1: "GROW YOUR WEALTH",
    heroSlide2TitleAccent: "WITH TAILORED ASSETS",
    heroSlide2Desc: "Optimize your investments, secure your assets, and profit from a custom investment strategy.",

    heroSlide3Badge: "Regional Financial Market",
    heroSlide3TitleLine1: "FINANCE YOUR GROWTH",
    heroSlide3TitleAccent: "FOR CORPORATES & STATES",
    heroSlide3Desc: "Strategic advisory for corporations and public institutions for capital raising and bond issuances.",

    heroBadge: "Licensed Stock Brokerage • CEMAC Zone",
    heroTitleMain: "Your Stock Brokerage Firm",
    heroTitleSub: "in Central Africa",
    heroDescSub: "Licensed by COSUMAF, member of BVMAC — invest with confidence in CEMAC financial markets with our certified experts.",
    openAccount: "OPEN AN ACCOUNT",
    bookAppointment: "BOOK AN APPOINTMENT",
    satisRate: "Satisfaction Rate",
    yearsExp: "Years of Experience",
    stat1Label: "YEARS OF EXPERIENCE",
    stat2Label: "TRUSTED CLIENTS",
    stat3Label: "SATISFACTION RATE",
    stat4Label: "CERTIFIED EXPERTS",

    // Why Choose Us
    aboutUsTag: "About Us",
    aboutUsHeading: "We Are a Stock Brokerage Firm",
    aboutUsHeadingAccent: "Dedicated to Your Success",
    aboutUsDesc: "For 5 years, OMYA INVEST guides its clients with rigor, transparency, and deep knowledge of CEMAC financial markets. Licensed by COSUMAF, we offer direct access to BVMAC.",
    secRegTitle: "Security & Regulation",
    secRegDesc: "Licensed stock brokerage firm by COSUMAF. Your funds are segregated and protected according to CEMAC standards.",
    perfTitle: "Performance & Returns",
    perfDesc: "Our managed portfolios consistently outperform benchmark indices in regional financial markets.",
    yearsExpTitle: "5 Years of Experience",
    yearsExpDesc: "CEMAC financial markets expert — Brazzaville, Congo.",
    clientTrustCount: "Clients trust us",
    discoverServices: "Discover Our Services",
    whyTitle: "WHY CHOOSE",
    whyTitleGold: "OMYA INVEST ?",
    whyDesc: "Our expertise, independence, and commitment to clients make us a trusted partner to achieve your financial goals.",

    // Activities Section
    missionVisionTag: "Our Mission & Vision",
    missionVisionHeading: "Discover the Core Principles That Guide Us",
    whatWeDoTag: "What We Do",
    whatWeDoDesc: "We guide our clients with rigor, transparency, and deep knowledge of Central African markets.",
    activitiesTitle: "OUR SERVICES & ACTIVITIES",
    learnMore: "LEARN MORE",
    act1Title: "STOCK BROKERAGE",
    act1Desc: "Order execution on financial markets, brokerage, and access to premier opportunities.",
    act2Title: "WEALTH MANAGEMENT",
    act2Desc: "Tailored solutions to grow and protect your wealth.",
    act3Title: "FINANCIAL ADVISORY",
    act3Desc: "Strategic guidance for your financial decisions and corporate projects.",
    act4Title: "INVESTMENTS",
    act4Desc: "Access to local and international investment opportunities.",

    // Markets Section
    marketsTag: "Real-Time Data",
    marketsTitle: "OUR FINANCIAL MARKETS",
    marketsSub: "Access real-time information on top markets and indices.",
    seeAllMarkets: "VIEW ALL MARKETS",
    mapCentralAfrica: "Central Africa",
    mapBEAC: "BEAC",
    mapBVMAC: "BVMAC",
    mapIntl: "Global Markets",
    tabIndices: "INDICES",
    tabActions: "STOCKS",
    tabObligations: "BONDS",
    tabDevises: "FOREX",
    trendText: "Trend",
    seeMoreDetails: "VIEW FULL DETAILS",

    // Products Section
    productsTag: "Tailored Solutions",
    productsTitle: "OUR INVESTMENT PRODUCTS",
    discover: "DISCOVER",
    prod1Title: "LISTED STOCKS",
    prod1Desc: "Invest in listed companies and capitalize on market growth potential.",
    prod2Title: "BONDS",
    prod2Desc: "Diversify your portfolio with secure fixed-income securities.",
    prod3Title: "MUTUAL FUNDS (OPCVM)",
    prod3Desc: "Access collective investment funds managed by our experts.",
    prod4Title: "GOVERNMENT SECURITIES",
    prod4Desc: "Safe investments issued by governments for steady income.",
    prod5Title: "PRIVATE EQUITY",
    prod5Desc: "Direct equity investments in high-potential unlisted companies.",

    // News, Simulator & Partners
    newsTitle: "FINANCIAL NEWS",
    seeAllNews: "VIEW ALL",
    simTitle: "INVESTMENT SIMULATOR",
    amountToInvest: "Amount to Invest",
    durationLabel: "Duration",
    yearSuffix: "years",
    estimatedRate: "Estimated Rate",
    estimatedResult: "Estimated Final Return",
    calculateBtn: "CALCULATE MY RETURN",
    partnersTitle: "OUR PARTNERS",
    seeAllPartners: "VIEW ALL",

    // Testimonials & Footer
    testimonialsTag: "Trust & Satisfaction",
    testimonialsTitle: "WHAT OUR CLIENTS SAY",
    ourTeamTitle: "Our Team of Experts",
    availableBadge: "Available",
    ctaTitle: "Let's Discuss Your Financial Goals & Get a",
    ctaTitleAccent: "Free Consultation",
    ctaDesc: "Our COSUMAF certified experts are available to analyze your situation and propose a tailored investment strategy.",
    getConsultation: "Get a Consultation",
    quickLinks: "QUICK LINKS",
    servicesLinks: "SERVICES",
    addressHoursTitle: "Address & Working Hours",
    openDaysTitle: "Working Days",
    openDaysValue: "Mon – Fri: 08:00 AM – 05:00 PM",
    contactUs: "CONTACT US",
    newsletterTitle: "NEWSLETTER",
    newsletterDesc: "Get our weekly market insights and financial updates.",
    emailPlaceholder: "Your email address",
    footerRights: "© 2024 OMYA INVEST. All rights reserved.",
    legalMentions: "Legal Notice",
    privacyPolicy: "Privacy Policy",
    siteMap: "Site Map",

    // Auth Modal
    authModalLoginTitle: "Access Your Account",
    authModalRegisterTitle: "Create Your Account",
    authModalLoginDesc: "Log in to track your investments and manage your portfolio.",
    authModalRegisterDesc: "Join OMYA INVEST and access stock market opportunities.",
    orByEmail: "or with email",
    fullName: "Full Name",
    emailAddr: "Email Address",
    passwordLabel: "Password",
    forgotPass: "Forgot?",
    investorType: "Investor Type",
    particulier: "Individual Investor",
    corporate: "Corporate / Institutional",
    rememberMe: "Remember me",
    acceptTerms: "I accept terms of service",
    submitLogin: "LOG IN",
    submitRegister: "SIGN UP",
  },
};

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState('FR');

  const t = translations[currentLang] || translations.FR;

  const changeLanguage = (code) => {
    if (translations[code]) setCurrentLang(code);
  };

  return (
    <LanguageContext.Provider value={{ currentLang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
